# Generated by Django 4.2.5 on 2023-09-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='done',
        ),
        migrations.AlterField(
            model_name='todo',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
